save_dir: train_pid
data:
  name: nexo
  h5file: /hpcfs/juno/junogpu/miaoyu/bb0n/dataset/strip_6mm/lzp/nexo_v0.h5
  csvfile: /hpcfs/juno/junogpu/miaoyu/bb0n/dataset/strip_6mm/lzp/nexo_v0.csv
  loss_acc_path: /hpcfs/juno/junogpu/miaoyu/bb0n/nEXO_ML/training_outputs/
  loss_acc_file: loss_acc_resnet18_largersample_0627
  modelpath: /hpcfs/juno/junogpu/miaoyu/bb0n/nEXO_ML/checkpoint_sens/
  modelfile: ckpt_resnet18_largesize_0627.t7
  train_split: 0.8
  input_shape:
  - 250
  - 250
  - 2
model:
  name: resnet18

fit:
  compile:
    initial_lr: 0.000001
    lr_decay: 0.99
    weight_decay: 0.0001
    optimizer: AdamW
    loss: CrossEntropyLoss
    DIV_factor: 10000
    grad_clip: 0.3
  epochs: 30
  patience: 1000
  batch_size: 400
  num_workers: 1
  log_interval: 20
